// Auto-generated by scrape-episodes.cjs — 2026-03-10T13:13:01.534Z
export const podcastMeta = {
  "title": "Le Temps Maîtrisé - Excellence opérationnelle dans l'horlogerie suisse",
  "description": "Bienvenue dans Le Temps Maîtrisé, le podcast qui explore les coulisses de l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode vous plonge au cœur des ateliers, des méthodes Lean et des outils qualité qui façonnent la précision et la beauté du temps.",
  "coverImage": "https://image.ausha.co/Qjf42vz69yOlOk88IwFbwxj6XxbJqGdlOkpBgqWs_1400x1400.jpeg?t=1761847626",
  "author": "Christophe Fournier",
  "link": "https://podcast.ausha.co/excellence-operationnelle"
};

export const podcasts = [
  {
    "id": "ep-1",
    "episodeNumber": 1,
    "title": "Épisode 1 – L’héritage de l’horlogerie suisse",
    "audioUrl": "https://audio.ausha.co/LjDL5C9kxN85.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep1.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/new-episode-of-10-30-7-13-pm",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-2",
    "episodeNumber": 2,
    "title": "Épisode 2 : Qu’est-ce que l’excellence opérationnelle ?",
    "audioUrl": "https://audio.ausha.co/aO1X5Uxpjna1.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep2.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-2-qu-est-ce-que-l-excellence-operationnelle",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-3",
    "episodeNumber": 3,
    "title": "Épisode 3 : La chasse au gaspillage – les 7 mudas",
    "audioUrl": "https://audio.ausha.co/ewZLXIppl7ZV.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep3.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-3-la-chasse-au-gaspillage-les-7-mudas",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-4",
    "episodeNumber": 4,
    "title": "Épisode 4 : Le 5S – l’ordre qui libère",
    "audioUrl": "https://audio.ausha.co/J2NYaij31OxV.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep4.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-4-le-5s-l-ordre-qui-libere",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-5",
    "episodeNumber": 5,
    "title": "Épisode 5 : Le standard de travail – la qualité répétable",
    "audioUrl": "https://audio.ausha.co/3mV5ZFMGvQp7.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep5.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-5-le-standard-de-travail-la-qualite-repetable",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-6",
    "episodeNumber": 6,
    "title": "Épisode 6 : Le management visuel – voir pour mieux comprendre",
    "audioUrl": "https://audio.ausha.co/YDvz1I88VQWk.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep6.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-6-le-management-visuel-voir-pour-mieux-comprendre",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-7",
    "episodeNumber": 7,
    "title": "Épisode 7 : Le Gemba – aller voir, écouter, comprendre",
    "audioUrl": "https://audio.ausha.co/PqxOXu28gmQG.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep7.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-7-le-gemba-aller-voir-ecouter-comprendre",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-8",
    "episodeNumber": 8,
    "title": "Épisode 8 : Le Kaizen – les petites améliorations au quotidien",
    "audioUrl": "https://audio.ausha.co/A82aWIk4KrVr.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep8.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-8-le-kaizen-les-petites-ameliorations-au-quotidien",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-9",
    "episodeNumber": 9,
    "title": "Épisode 9 : La résolution de problème – penser autrement",
    "audioUrl": "https://audio.ausha.co/nZw21cKZEDaG.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep9.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-9-la-resolution-de-probleme-penser-autrement",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-10",
    "episodeNumber": 10,
    "title": "Épisode 10 : Le takt time – équilibrer le rythme de production",
    "audioUrl": "https://audio.ausha.co/xAz3wsw0N6VE.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep10.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-10-le-takt-time-equilibrer-le-rythme-de-production",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-11",
    "episodeNumber": 11,
    "title": "Épisode 11 : L’autonomation – détecter sans contrôle final",
    "audioUrl": "https://audio.ausha.co/Ggk0wu8gk458.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep11.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-11-l-autonomation-detecter-sans-controle-final",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  },
  {
    "id": "ep-12",
    "episodeNumber": 12,
    "title": "Épisode 12 – Cultiver l’excellence : le lean à l’ère du digital et de l’IA",
    "audioUrl": "https://audio.ausha.co/zr84aIVvM8a6.mp3\\",
    "description": "Le Temps Maîtrisé - une série de Christophe Fournier dédiée à l'excellence opérationnelle dans l'horlogerie suisse. Chaque épisode explore les outils du Lean, la qualité et la précision, appliqués à un univers où le temps se mesure au micron.",
    "image": "/infographics/ep12.png",
    "link": "https://podcast.ausha.co/excellence-operationnelle/episode-12-cultiver-l-excellence-le-lean-a-l-ere-du-digital-et-de-l-ia",
    "keywords": [
      "excellence opérationnelle",
      "lean management",
      "horlogerie",
      "suisse",
      "qualité"
    ]
  }
];
